### ISSUE TITLE
api for openshift has changed?

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/openshift-rest-client#42]
when doing some tests with the vert.x boosters(also wfswarm booster), i noticed that the endpoints that they were interacting with were slightly different than what they were originally.

For example, i was looking at how to delete and recreate a build or build config.

It used to be somthing like this: /oapi/v1/namespaces/NAMESPACE/build/BUILD_NAME

but now it looks something like this:  /apis/build.openshift.io/v1/namespace.......

Not sure when that change was made,  and i wonder if we should be changing our code ?

"older" oapi endpoints are still there

**Comment by lance** [comment]
Any changes should be a part of major refactor
