### ISSUE TITLE
Include the config-loader again

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/openshift-rest-client#54]
After talking with @lance, we decided it might be better to have the config loader integrated back into this library.

I think if no config is passed, then it just does the default stuff(calls config-loader), but if a config is passed in, then it will use that instead  

I think i was trying to be to smart with this https://github.com/bucharest-gold/openshift-rest-client/issues/5

**Comment by lholmquist** [comment]
This will change the method signature from `func(config, settings)` to just `func(settings)`

if you still want to pass in a custom config object,  add it to `settings.config`, likewise, if you need to override something in the config loader, pass that in with `settings.openshiftConfigLoader`

Once this change is in, we will probably bump to 1.0.0 since it is a breaking change

**Comment by lholmquist** [comment]
@tavogel wanted to give you a heads up

**Comment by tavogel** [comment]
Thanks. This will be breaking as we don't use local configuration but as long as we can still override it should be ok

**Comment by lholmquist** [comment]
@tavogel yea,  you can override using `settings.config = {...}`

**Comment by lholmquist** [comment]
@tavogel if you wanted to give the new version a try, i created a "canary" version as 0.12.0-0
